### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ImageNotFound' while invoking the simpliest python lambda

### ISSUE THREAD

**Issue by makskant** [awslabs/aws-sam-cli#560]
**Description:**

After upgrading to 0.5 version, hoping to solve old new line bug, still not able to test a simple lambda function in python locally, now because of some docker image name error

**Steps to reproduce the issue:**
1. Function handler
```
def handler(event, context):
    return {'body': json.dumps([]), 'statusCode': 200, 'headers': {"Cache-Control":"max-age=1200"}}
```
2. Resource
```
    TestFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: test.handler
            Role: !GetAtt FunctionRole.Arn
            CodeUri: functions/
            AutoPublishAlias: live
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /test
                        Method: get

```

3. Running `sam local start-api` and trying to requests a http://127.0.0.1:3000/test

**Observed result:**
```
[2018-07-17 17:43:04,698] ERROR in app: Exception on /test [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/samcli/local/apigw/service.py", line 161, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "/usr/local/lib/python2.7/dist-packages/samcli/commands/local/lib/local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "/usr/local/lib/python2.7/dist-packages/samcli/local/lambdafn/runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "/usr/local/lib/python2.7/dist-packages/samcli/local/docker/manager.py", line 52, in run
    if not self.has_image(image_name) or not self.skip_pull_image:
  File "/usr/local/lib/python2.7/dist-packages/samcli/local/docker/manager.py", line 110, in has_image
    except docker.errors.ImageNotFound:
AttributeError: 'module' object has no attribute 'ImageNotFound'

```
**Expected result:**
Expecting to have an empty array as a response with status code 200

**OS**: Ubuntu 16.04

**Output of `sam --version`**: 0.5.0

**Python version**: 3.6.1.

**Optional Debug logs**:

```
2018-07-17 17:55:06 Found one Lambda function with name 'TestFunction'
2018-07-17 17:55:06 Invoking test.handler (python3.6)
2018-07-17 17:55:06 Environment variables overrides data is standard format
2018-07-17 17:55:06 Loading AWS credentials from session with profile 'None'
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable config_file from defaults.
2018-07-17 17:55:06 Loading variable credentials_file from defaults.
2018-07-17 17:55:06 Loading variable data_path from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable credentials_file from defaults.
2018-07-17 17:55:06 Loading variable config_file from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable metadata_service_timeout from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable metadata_service_num_attempts from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Looking for credentials via: env
2018-07-17 17:55:06 Looking for credentials via: assume-role
2018-07-17 17:55:06 Looking for credentials via: shared-credentials-file
2018-07-17 17:55:06 Found credentials in shared credentials file: ~/.aws/credentials
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable region from config file with value 'eu-central-1'.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable region from config file with value 'eu-central-1'.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable profile from defaults.
2018-07-17 17:55:06 Loading variable region from config file with value 'eu-central-1'.
2018-07-17 17:55:06 Resolving code path. Cwd=/home/msukhorukov/Documents/awspy, CodeUri=functions/
2018-07-17 17:55:06 Resolved absolute path to code is /home/msukhorukov/Documents/awspy/functions
2018-07-17 17:55:06 Code /home/msukhorukov/Documents/awspy/functions is not a zip/jar file
2018-07-17 17:55:06 Trying paths: ['/home/msukhorukov/.docker/config.json', '/home/msukhorukov/.dockercfg']
2018-07-17 17:55:06 No config file found
2018-07-17 17:55:06 Container was not created. Skipping deletion
2018-07-17 17:55:06 Exception on /test [GET]
Traceback (most recent call last):
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 140, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/samcli/local/lambdafn/runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/samcli/local/docker/manager.py", line 52, in run
    if not self.has_image(image_name) or not self.skip_pull_image:
  File "/home/msukhorukov/.local/lib/python2.7/site-packages/samcli/local/docker/manager.py", line 110, in has_image
    except docker.errors.ImageNotFound:
AttributeError: 'module' object has no attribute 'ImageNotFound'
2018-07-17 17:55:06 127.0.0.1 - - [17/Jul/2018 17:55:06] "GET /test HTTP/1.1" 502 -
2018-07-17 17:55:06 127.0.0.1 - - [17/Jul/2018 17:55:06] "GET /favicon.ico HTTP/1.1" 403 -
```

**Comment by jfuss** [comment]
@makskant Your template does define a `Runtime`. Can you add the correct runtime and try again?

**Comment by makskant** [comment]
```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
 
Globals:
    Function:
        Timeout: 5
        Runtime: python3.6
    Api:
        Cors: "'*'"

Resources:
    TestFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: test.handler
            Role: !GetAtt FunctionRole.Arn
            CodeUri: functions/
            AutoPublishAlias: live
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /test
                        Method: get
# ...
```

@jfuss, we have runtime defined globally for all functions

**Comment by jfuss** [comment]
@makskant Ahh. I was looking at the output further and looks like it can't find `ImageNotFound` in the docker.exception module. Can you do a pip freeze and tell me what version of docker you have?

**Comment by makskant** [comment]
@jfuss 
```bash
docker==3.4.1
```

**Comment by jfuss** [comment]
@makskant hmmm... It looks to be there: https://github.com/docker/docker-py/blob/3.4.1-release/docker/errors.py#L81

This is screaming a pip/python version issue to me. You commented that you are using 3.6.1 for the python version, but the commands look like it is using 2.7. Do you have a pip3 too? These are sometime hard to track down. I would first start by uninstall aws-sam-cli and try running `sam`. This should at least give us an indication of if there are two clis installed. From there you might be able to track down where this lives.

The output for `which sam` might give you some clues off the bat as well.

**Comment by makskant** [comment]
@jfuss indeed. `docker==3.4.1` was for python 3.6.1, for python2 i had `docker ==3.3.0`, i have upgraded for python2 it and it worked just fine. thank you

**Comment by jfuss** [comment]
@makskant That is weird but 3.3.0 should also have the error (ImageNotFound was committed 2 or 3 years ago) and 3.3.0 is what we [depend on](https://github.com/awslabs/aws-sam-cli/blob/develop/requirements/base.txt#L9).

Either way, the cli supports Py3.6. So you can install and get rid of py2 (as long as nothing else needs it of course).

Regardless, glad its resolved :)
